import Head from "next/head";
import Index from "../components/index.jsx";
import Contacts from "../components/contacts.jsx";
import Footer from "../components/footer-component.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>GameCloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Index />
      <Contacts />
      <Footer />

    </>
  );
}
