import Head from "next/head";
import Header from "@/components/Header";
import Main from '../components/Main'
import Contacts from "@/components/Contacts";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>GameCloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main />
      <Contacts />
      <Navbar/>
      <Footer />

    </>
  );
}
